# Generated by Django 2.2.4 on 2019-10-16 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polis',
            name='identification_number',
            field=models.CharField(default=uuid.UUID('12e10c6e-88d6-4441-b531-779ea448ddb9'), editable=False, max_length=32),
        ),
    ]
