# Generated by Django 2.2.4 on 2019-10-16 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0002_auto_20191016_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polis',
            name='identification_number',
            field=models.CharField(default=uuid.UUID('3a06598f-63bc-4dc9-a5b2-2afa39021920'), editable=False, max_length=128),
        ),
    ]
