# Generated by Django 2.2.4 on 2019-10-17 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0003_auto_20191016_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polis',
            name='identification_number',
            field=models.CharField(default=uuid.UUID('86f8e21f-f3fb-401b-9fa9-44d8ae57a9a0'), editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='polis',
            name='type',
            field=models.IntegerField(choices=[('MANDATORY', 'ОМС'), ('VOLUNTARY', 'ДМС')]),
        ),
    ]
