# Generated by Django 2.2.4 on 2019-10-17 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0004_auto_20191017_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polis',
            name='identification_number',
            field=models.IntegerField(default=uuid.UUID('eee939ef-0363-4677-86a8-cdc57687affb'), editable=False),
        ),
        migrations.AlterField(
            model_name='polis',
            name='type',
            field=models.IntegerField(choices=[('MANDATORY', 'ОМС'), ('VOLUNTARY', 'ДМС')], max_length=12),
        ),
    ]
