# Generated by Django 2.2.4 on 2019-10-17 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0005_auto_20191017_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polis',
            name='identification_number',
            field=models.IntegerField(default=uuid.UUID('459b2201-8818-42e2-be46-189ef3787b1e'), editable=False),
        ),
    ]
