# Generated by Django 2.2.4 on 2019-10-17 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0006_auto_20191017_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polis',
            name='identification_number',
            field=models.IntegerField(default=uuid.UUID('d691b99c-a31e-4cd7-99b1-9dc22051612f'), editable=False),
        ),
        migrations.AlterField(
            model_name='polis',
            name='type',
            field=models.CharField(choices=[('MANDATORY', 'ОМС'), ('VOLUNTARY', 'ДМС')], max_length=12),
        ),
    ]
