# Generated by Django 2.2.4 on 2019-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0007_auto_20191017_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polis',
            name='identification_number',
            field=models.CharField(default='7383669605006867', editable=False, max_length=16, unique=True),
        ),
    ]
