# Generated by Django 2.2.4 on 2019-10-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0010_auto_20191018_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polis',
            name='medical_services',
        ),
    ]
