# Generated by Django 2.2.4 on 2019-10-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0014_auto_20191019_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polis',
            name='identification_number',
            field=models.DecimalField(max_digits=16, decimal_places=4, unique=True),
        ),
    ]
