# Generated by Django 2.2.4 on 2019-10-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0015_auto_20191019_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polis',
            name='identification_number',
        ),
    ]
