# Generated by Django 2.2.4 on 2019-10-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med_ask_test_app', '0022_auto_20191020_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservice',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
